// Code generated by @gugbab/types-generator. DO NOT EDIT.
// Source: /var/folders/n_/6vv06yqd3pn340sf9_f380y40000gn/T/relay-openapi.json
// Generated: 2026-07-08T05:10:38.329Z

export interface paths {
    "/api/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Claude SSE 스트리밍 채팅
         * @description 요청을 Claude CLI로 중계하고 SSE(text/event-stream)로 응답을 스트리밍합니다.
         *
         *     **SSE 스트림 형식**: 각 이벤트는 `data: <JSON>\n\n` 줄로 전달됩니다.
         *     응답 스키마는 `SSEEvent`(oneOf: SSEChunk / SSEDone / SSEError)를 참조하세요.
         *
         *     **스킬 주입 순서**: `systemPrompt` (있을 경우) → 앱별 SKILL.md 내용
         */
        post: operations["chatStream"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 사용 가능한 Claude 모델 목록
         * @description relay가 지원하는 Claude 모델 목록과 기본 모델 alias를 반환합니다. 인증 불필요.
         */
        get: operations["listModels"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description 지원하는 앱 식별자. 해당 앱의 SKILL.md를 자동 주입합니다.
         * @enum {string}
         */
        AppType: "dream" | "health";
        /**
         * @description 메시지 작성자 역할
         * @enum {string}
         */
        MessageRole: "user" | "assistant";
        /**
         * @description Claude 모델 alias. 내부적으로 전체 모델 ID로 변환됩니다.
         *
         *     | alias | 모델 ID | 특성 |
         *     |-------|---------|------|
         *     | `haiku` | `claude-haiku-4-5-20251001` | 빠르고 가벼움 — 간단한 질문·빠른 응답에 최적 |
         *     | `sonnet` | `claude-sonnet-4-6` | 속도·품질 균형 — 일반적인 대화에 권장 (기본값) |
         *     | `opus` | `claude-opus-4-8` | 최고 품질 — 복잡한 꿈 해석·심층 영양 분석에 적합 |
         *     | `fable` | `claude-fable-5` | 최상위 모델 — 가장 정교한 추론, 비용 높음 |
         * @enum {string}
         */
        ModelAlias: "haiku" | "sonnet" | "opus" | "fable";
        Message: {
            role: components["schemas"]["MessageRole"];
            /** @description 메시지 내용 */
            content: string;
        };
        ChatRequest: {
            app: components["schemas"]["AppType"];
            /** @description 커스텀 시스템 프롬프트 (선택). 제공 시 SKILL.md 앞에 prepend됩니다. 빈 문자열 불가. */
            systemPrompt?: string;
            /** @description 대화 히스토리. 첫 번째·마지막 메시지는 반드시 role=user여야 합니다. */
            messages: components["schemas"]["Message"][];
            /**
             * @description 사용할 모델 alias. 생략 시 기본값: sonnet (→ claude-sonnet-4-6)
             * @default sonnet
             */
            model: components["schemas"]["ModelAlias"];
        };
        /** @description 텍스트 델타 이벤트 */
        SSEChunk: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "chunk";
            /** @description 이전 chunk 이후 추가된 텍스트 조각 */
            text: string;
        };
        /** @description 스트리밍 완료 이벤트 */
        SSEDone: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "done";
        };
        /** @description 오류 이벤트 (스트림 내 인라인) */
        SSEError: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "error";
            /** @description 오류 메시지 */
            message: string;
        };
        SSEEvent: components["schemas"]["SSEChunk"] | components["schemas"]["SSEDone"] | components["schemas"]["SSEError"];
        /**
         * @description API 에러 코드
         * @enum {string}
         */
        ErrorCode: "UNAUTHORIZED" | "VALIDATION_ERROR" | "INVALID_JSON";
        ErrorResponse: {
            /** @description HTTP 상태 코드 */
            status: number;
            /** @description HTTP 상태 텍스트 (e.g. "Unauthorized") */
            error: string;
            errorCode: components["schemas"]["ErrorCode"];
            /** @description 사용자 안내 메시지 */
            message: string;
        };
        ModelInfo: {
            /** @description Claude 모델 전체 ID */
            id: string;
            alias: components["schemas"]["ModelAlias"];
            /** @description 표시 이름 */
            name: string;
            /** @description 모델 특성 설명 */
            description: string;
        };
        ModelsResponse: {
            /** @description 사용 가능한 모델 목록 */
            models: components["schemas"]["ModelInfo"][];
            /**
             * @description 기본값으로 사용되는 모델 alias
             * @example sonnet
             */
            default: components["schemas"]["ModelAlias"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    chatStream: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description SSE 스트림 시작. 각 줄은 `data: <SSEEvent JSON>\n\n` 형식. */
            200: {
                headers: {
                    "Content-Type"?: string;
                    "Cache-Control"?: string;
                    "X-Accel-Buffering"?: string;
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example data: {"type":"chunk","text":"이가 빠지는 꿈은"}
                     *
                     *     data: {"type":"chunk","text":" 불안을 상징합니다."}
                     *
                     *     data: {"type":"done"}
                     */
                    "text/event-stream": string;
                };
            };
            /** @description 잘못된 요청 (Zod 검증 실패) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 인증 실패 (X-Relay-Secret 없거나 불일치) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listModels: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 모델 목록 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "models": [
                     *         {
                     *           "id": "claude-haiku-4-5-20251001",
                     *           "alias": "haiku",
                     *           "name": "Claude Haiku 4.5",
                     *           "description": "빠르고 가벼움 — 간단한 질문·빠른 응답에 최적"
                     *         },
                     *         {
                     *           "id": "claude-sonnet-4-6",
                     *           "alias": "sonnet",
                     *           "name": "Claude Sonnet 4.6",
                     *           "description": "속도·품질 균형 — 일반적인 대화에 권장 (기본값)"
                     *         },
                     *         {
                     *           "id": "claude-opus-4-8",
                     *           "alias": "opus",
                     *           "name": "Claude Opus 4.8",
                     *           "description": "최고 품질 — 복잡한 꿈 해석·심층 영양 분석에 적합"
                     *         },
                     *         {
                     *           "id": "claude-fable-5",
                     *           "alias": "fable",
                     *           "name": "Claude Fable 5",
                     *           "description": "최상위 모델 — 가장 정교한 추론, 비용 높음"
                     *         }
                     *       ],
                     *       "default": "sonnet"
                     *     }
                     */
                    "application/json": components["schemas"]["ModelsResponse"];
                };
            };
        };
    };
}
