import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { pathToFileURL } from "node:url";
import openapiTS, { astToString } from "openapi-typescript";

export interface GenerateTypesOptions {
    /** OpenAPI JSON의 HTTP URL 또는 로컬 파일 경로 */
    input: string;
    /** 생성될 .ts 파일 경로 */
    output: string;
}

export async function generateTypes(options: GenerateTypesOptions): Promise<void> {
    const { input, output } = options;

    const source = /^https?:\/\//.test(input) ? new URL(input) : pathToFileURL(resolve(input));
    const ast = await openapiTS(source);
    const contents = astToString(ast);

    const header =
        "// Code generated by @gugbab/types-generator. DO NOT EDIT.\n" +
        `// Source: ${input}\n` +
        `// Generated: ${new Date().toISOString()}\n\n`;

    writeFileSync(resolve(output), header + contents, "utf-8");
    console.log(`✓ Generated types → ${output}`);
}
